db:
  image: postgres
  ports:
    - 5432:5432
event-tracker:
  build: .
  volumes:
    - .:/usr/app
  ports:
    - 80:3000
  links:
    - db
  environment:
    - PGHOST=db
    - PGPORT=5432
    - PGDATABASE=events
    - PGUSER=postgres
    - PGPASSWORD=postgres